config/routes.rb
CantineTest1::Application.routes.draw do
  

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  devise_for :users
  resources :users, :only => [:show, :index]

  resources :recettes

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
      can :manage, Recette, :user_id => user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/recette.rb
class Recette < ActiveRecord::Base
	resourcify
  attr_accessible :description, :ingredients, :preparation, :titre

  belongs_to :user

  validates :user_id, :presence => true

  default_scope :order => 'recettes.created_at DESC'

  validates :titre, :presence => true
  
  validates :description, :presence => true

  validates :ingredients, :presence => true

  validates :preparation, :presence => true

  



end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :recettes, :dependent => :destroy

  validates :name, :presence => true,
                    :length => { :maximum => 50 },
                    :uniqueness => { :case_sensitive => false }


  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#load_and_authorize_resource
  def index
	  @users = User.all
	  @recettes = Recette.paginate(:page => params[:page], :per_page => 5)
	end
end

app/controllers/recettes_controller.rb
#!/bin/ruby
# encoding: utf-8

class RecettesController < InheritedResources::Base
	#before_filter :authenticate_user!, :only => [:new, :create, :edit, :destroy]
	#before_filter :authorized_user, :only => [:edit, :destroy]

	load_and_authorize_resource
	#skip_authorize_resource :only => [:new, :create]

	def index
	    @recettes = Recette.all
	end


	def new
		@recette = current_user.recettes.new	   
    end

    def create
    	@recette = current_user.recettes.build(params[:recette])
    	if @recette.save
    		flash[:success] = "Recette créée !"
    		redirect_to root_path
    	else
    		render 'new'
    	end
    end

    



	def destroy
		@recette.destroy
		redirect_to root_path
	end


	

	private
		def authorized_user
	      @recette = Recette.find(params[:id])
	      redirect_to root_path unless current_user == @recette.user
	    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   #before_filter :authenticate_user!, :except => [:index, :show]
   load_and_authorize_resource


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @liste_recettes = @user.recettes.paginate(:page => params[:page], :per_page => 5)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	def users
		@users = User.all
	end
	def affichage_bouttons?
		current_user.has_role? :admin or current_user == @recette.user
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recettes_helper.rb
module RecettesHelper

	def affichage_bouttons?
		current_user.has_role? :admin or current_user == @recette.user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Les dernières recettes</h1>
<%= will_paginate @recettes, :class => 'pager' %>
<% @recettes.each do |recette| %>
	<%= render :partial => 'shared/bloc_recette', :locals => { :recette => recette } %>
<% end %>
<%= will_paginate @recettes, :class => 'pager' %>

app/views/layouts/_footer.html.erb
<footer>
        <p>&copy; Ma Cantine : test1 - 2012</p>
      </footer>

app/views/layouts/_head.html.erb
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CantineTest1" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Ma Cantine<% if signed_in? %> | <%= current_user.name %><% end %></a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if signed_in? %>
                <li><%= link_to "Proposer une recette", new_recette_path %></li>
                <li><%= link_to "Déconnexion", destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to "S'identifier", new_user_session_path %></li>
                <li><%= link_to "S'inscrire", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
<h3>Liste des utilisateurs</h3>
<ul class="nav nav-list">
	<% users.each do |user| %>
  	<li><%= link_to user.name, user  %></li>
  <% end %>
</ul>
</div><!--/.well -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <%= render 'layouts/sidebar' %>
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/recettes/_form.html.erb
<%= form_for(@recette) do |f| %>
  <% if @recette.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recette.errors.count, "error") %> prohibited this recette from being saved:</h2>

      <ul>
      <% @recette.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field left">
    <%= f.label :titre %><br />
    <%= f.text_field :titre %>
  </div>
  <div class="row">
    <div class="field span3">
      <%= f.label :description %><br />
      <%= f.text_area :description %>
    </div>
    <div class="field span3">
      <%= f.label :ingredients %><br />
      <%= f.text_area :ingredients %>
    </div>
    <div class="field span3">
      <%= f.label :preparation %><br />
      <%= f.text_area :preparation %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recettes/edit.html.erb
<h1>Editing recette</h1>

<%= render 'form' %>

<%= link_to 'Show', @recette %> |
<%= link_to 'Back', root_path %>

app/views/recettes/index.html.erb
<h1>Listing recettes</h1>

<table>
  <tr>
    <th>Titre</th>
    <th>Description</th>
    <th>Ingredients</th>
    <th>Preparation</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recettes.each do |recette| %>
  <tr>
    <td><%= recette.titre %></td>
    <td><%= recette.description %></td>
    <td><%= recette.ingredients %></td>
    <td><%= recette.preparation %></td>
    <td><%= recette.user_id %></td>
    <td><%= link_to 'Show', recette %></td>
    <td><%= link_to 'Edit', edit_recette_path(recette) %></td>
    <td><%= link_to 'Destroy', recette, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recette', new_recette_path %>

app/views/recettes/new.html.erb
<h1>Nouvelle recette par <%= current_user.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/recettes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @recette.titre %>
</h1>

<p>
  <b>Description:</b>
  <%= @recette.description %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @recette.ingredients %>
</p>

<p>
  <b>Preparation:</b>
  <%= @recette.preparation %>
</p>

<p>
  <b>User:</b>
  <%= @recette.user.name %>
</p>
<% if current_user.nil? %>
  <%= link_to 'Back', root_path %>
<% else %>
  <% if affichage_bouttons? %>
    <%= link_to 'Edit', edit_recette_path(@recette) %> |
    <%= link_to 'Destroy', @recette, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>
  <%= link_to 'Back', root_path %>
<% end %>

app/views/shared/_bloc_recette.html.erb
<div class="well">
	<div class="row">
        <div class="span3">
        	<h2><%= link_to recette.titre, recette %></h2>
        </div>
	    <div class="span3">
	    	<p><%= recette.description %></p>
	    </div>
	    <div class="span2">
	    	<p>Proposé par : <%= link_to recette.user.name, recette.user %></p>
	    	<p>Le <%= recette.created_at %> </p>
	    	<% if current_user.nil? %>

	    	<% else %>
		    	<% if current_user == recette.user or current_user.has_role? :admin %>
				  <%= link_to 'Edit', edit_recette_path(recette) %> |
				  <%= link_to 'Destroy', recette, method: :delete, data: { confirm: 'Are you sure?' } %> |
				<% end %>
			<% end %>

	    </div>
    </div>
</div>

app/views/users/index.html.erb
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<% if current_user == @user %>
	<h1><%= @user.name %></h1>
	<h2>Mes Recettes : </h2>
<% else %>
	<h1>Les recettes de <%= @user.name %></h1>
<% end %>

<% if @liste_recettes.empty? %>
	<p><%= @user.name %> n'a pas encore publié de recette</p>
<% else %>
	<%= will_paginate @liste_recettes, :class => 'pager' %>
	<% @liste_recettes.each do |recette| %>
		<%= render :partial => 'shared/bloc_recette', :locals => { :recette => recette } %>
	<% end %>
	<%= will_paginate @liste_recettes, :class => 'pager' %>
<% end %>